name: CI

on: push

jobs:
  e2e-test:
    strategy:
      matrix:
        provider: [vercel, cloudflare, local]
    uses: jill64/playwright-config/.github/workflows/run-playwright.yml@c5b02b99d0d7b9725a10ccf14579da07cceaedab # v2.2.6
    with:
      test-command: npx playwright test
      hosting-provider: ${{ matrix.provider }}
