name: CI

on: push

jobs:
  e2e-test:
    # strategy:
    #   matrix:
    #     provider: [vercel, netlify, cloudflare]
    uses: jill64/.github/.github/workflows/run-playwright.yml@main
    with:
      # test-command: export PREVIEW_URL=${{ matrix.provider == 'vercel' && vars.VERCEL_PREVIEW_URL || matrix.provider == 'netlify' && vars.NETLIFY_PREVIEW_URL || vars.CLOUDFLARE_PREVIEW_URL }} && npx playwright test
      test-command: export PREVIEW_URL=${{ vars.CLOUDFLARE_PREVIEW_URL }} && npx playwright test
