name: CI

on: push

jobs:
  e2e-test:
    strategy:
      matrix:
        provider: [vercel, cloudflare, local]
    uses: jill64/playwright-config/.github/workflows/run-playwright.yml@3493dea571274fa5ca79ec1597d7cfff848aa916 # v2.2.0
    with:
      test-command: npx playwright test
      hosting-provider: ${{ matrix.provider }}
