name: CI

on: push

jobs:
  e2e-test:
    strategy:
      matrix:
        provider: [vercel, cloudflare, local]
    uses: jill64/playwright-config/.github/workflows/run-playwright.yml@87d42c8a5b69f14d6af1cccf1ae38a9a778570dc # v2.3.0
    with:
      test-command: npx playwright test
      hosting-provider: ${{ matrix.provider }}
