name: CI

on: push

jobs:
  e2e-test:
    strategy:
      matrix:
        provider: [vercel, netlify, cloudflare]
    uses: jill64/.github/.github/workflows/run-playwright.yml@main
    with:
      test-command: export HOSTING_PROVIDER=${{ matrix.provider }} && npx playwright test
