name: CI

on: push

jobs:
  e2e-test:
    strategy:
      matrix:
        provider: [vercel, cloudflare, local]
    uses: jill64/playwright-config/.github/workflows/run-playwright.yml@33108f25a71d0f30636b531223a62692a9559601 # v2.4.2
    with:
      test-command: npx playwright test
      hosting-provider: ${{ matrix.provider }}
