name: CI

on: push

jobs:
  e2e-test:
    strategy:
      matrix:
        provider: [vercel, cloudflare, local]
    uses: jill64/playwright-config/.github/workflows/run-playwright.yml@164f3196faa6d87424822469d554d5a1ad7464ac # v2.4.1
    with:
      test-command: npx playwright test
      hosting-provider: ${{ matrix.provider }}
