name: CI

on: push

jobs:
  e2e-test:
    strategy:
      matrix:
        provider: [vercel, netlify, cloudflare, 'local']
    uses: jill64/playwright-config/.github/workflows/run-playwright.yml@v2.1.0
    with:
      test-command: npx playwright test
      hosting-provider: ${{ matrix.provider }}
